#!/usr/bin/env bash
# Deploy the read-only dashboard to Cloud Run, publicly accessible.
#
# Uses aksha-dashboard-reader, NOT aksha-runtime: the dashboard has no write
# path anywhere in its code (every Firestore call in aksha_agent/dashboard/app.py
# is .stream()/.get()/.count()), and the service account backs that at the IAM
# layer too, not just by code review. roles/datastore.viewer grants read-only
# access to Firestore (Datastore and Firestore Native share the datastore.*
# permission namespace) -- no write, delete, or admin permission at all.
#
# `gcloud run deploy --source` builds from a single directory, so this stages
# exactly what the image needs -- same pattern as deploy_detector.sh and
# deploy_triage.sh. The signal cache parquet and funnel stats are copied from
# whatever is on local disk right now, not from git (both are real files
# regenerated by scripts/precompute_signal_cache.py and
# scripts/build_funnel_stats.py, not something this script invents).
#
# Usage:  scripts/deploy_dashboard.sh [PROJECT_ID] [REGION]
set -euo pipefail

PROJECT="${1:-aksha-hackathon}"
REGION="${2:-us-central1}"
SERVICE="dashboard"
READER_SA_NAME="aksha-dashboard-reader"
READER_SA="${READER_SA_NAME}@${PROJECT}.iam.gserviceaccount.com"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${REPO_ROOT}/aksha_agent/infra/dashboard"
SIGNAL_CACHE="${REPO_ROOT}/data/processed/dashboard_signal_cache.parquet"
FUNNEL_STATS="${REPO_ROOT}/aksha_core/artifacts/mission2_funnel_stats.json"
FINAL_REPORT="${REPO_ROOT}/eval/outputs/final_report.json"

if [[ ! -f "${SIGNAL_CACHE}" ]]; then
  echo "signal cache missing: ${SIGNAL_CACHE}" >&2
  echo "build it first:  python3 scripts/precompute_signal_cache.py" >&2
  exit 1
fi
if [[ ! -f "${FUNNEL_STATS}" ]]; then
  echo "funnel stats missing: ${FUNNEL_STATS}" >&2
  echo "build it first:  python3 scripts/build_funnel_stats.py" >&2
  exit 1
fi

# Idempotent: create the read-only service account if it does not exist yet,
# and (re-)assert its one IAM binding. Safe to re-run.
if ! gcloud iam service-accounts describe "${READER_SA}" --project "${PROJECT}" >/dev/null 2>&1; then
  echo "creating ${READER_SA} ..."
  gcloud iam service-accounts create "${READER_SA_NAME}" \
    --project "${PROJECT}" \
    --display-name "AKSHA dashboard (read-only Firestore)"
fi
gcloud projects add-iam-policy-binding "${PROJECT}" \
  --member "serviceAccount:${READER_SA}" \
  --role "roles/datastore.viewer" \
  --condition None \
  --quiet >/dev/null

STAGE="$(mktemp -d)"
trap 'rm -rf "${STAGE}"' EXIT

cp "${SRC}/Dockerfile" "${SRC}/requirements.txt" "${STAGE}/"
mkdir -p "${STAGE}/aksha_agent/dashboard" "${STAGE}/data/processed" "${STAGE}/aksha_core/artifacts" "${STAGE}/.streamlit"
cp "${REPO_ROOT}/aksha_agent/dashboard/app.py" "${STAGE}/aksha_agent/dashboard/"
cp "${REPO_ROOT}/.streamlit/config.toml" "${STAGE}/.streamlit/"
cp "${SIGNAL_CACHE}" "${STAGE}/data/processed/"
cp "${FUNNEL_STATS}" "${STAGE}/aksha_core/artifacts/"
if [[ -f "${FINAL_REPORT}" ]]; then
  mkdir -p "${STAGE}/eval/outputs"
  cp "${FINAL_REPORT}" "${STAGE}/eval/outputs/"
fi

echo "staged for build:"
( cd "${STAGE}" && find . -type f | sort | sed 's/^/  /' )
echo

gcloud run deploy "${SERVICE}" \
  --source "${STAGE}" \
  --project "${PROJECT}" \
  --region "${REGION}" \
  --allow-unauthenticated \
  --service-account "${READER_SA}" \
  --min-instances 0 \
  --max-instances 2 \
  --memory 1Gi \
  --set-env-vars "GOOGLE_CLOUD_PROJECT=${PROJECT}" \
  --quiet
